import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import MainLayout from "@/components/MainLayout";

const fontSans = Poppins({
  weight: "400",
  variable: "--font-poppins-sans",
});

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export const metadata: Metadata = {
  title: {
    default: "Kryptonyme VPN",
    template: "%s | Kryptonyme VPN",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`bg-background text-foreground font-sans antialiased ${fontSans.variable}`}
      >
        <Providers
          themeProps={{ attribute: "class", defaultTheme: "light" }}
          className="min-h-screen flex flex-col"
        >
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
